<!-- TOC -->

- [1. 抛出异常相关关键字](#1-抛出异常相关关键字)
- [2. throw 关键字](#2-throw-关键字)
  - [2.1. 执行语法](#21-执行语法)
  - [2.2. 应用场景](#22-应用场景)
- [3. throws 关键字](#3-throws-关键字)

<!-- /TOC -->

## 1. 抛出异常相关关键字
- `throw` 关键字
- `throws` 关键字

## 2. throw 关键字

### 2.1. 执行语法
- 运用于方法内部, 抛出一个具体的异常对象. 然后终止方法, 类似 `return`.
  ```java
  throw new SomeException("Reason of Exception");
  ```

- 这个抛出的异常可以在 `catch` 中截取并获取其中的信息.

### 2.2. 应用场景
- 一般来说, 当一个方法出现异常的时候, 此时用 `return` 难以定义返回的内容,   
  因此可用 `throw` 返回一个异常对象, 在 `catch` 代码块中继续向上抛出异常.  
  所以必须先在 `try` 代码块中对该方法进行调用, 才能 `catch` 到异常.

- `return` 是返回一个值, `throw` 是返回一个错误, 返回给方法的调用者.

## 3. throws 关键字
- 运用于方法声明之上, 用于表示当前方法不处理异常, 而是提醒方法调用者来处理异常.
  ```java
  //因为除数为0这种异常并非编码人员导致
  //是使用该方法的人所导致, 因此不需要编码人员处理
  public int divide(int num1, int num2) throws Exception{
    if(num2 == 0){
      throws new Exception("除数不能为零!");
    }
    //TODO...
  }
  ```

- 如果每个方法都放弃处理异常, 都直接通过 `throws` 声明抛出,  
  最后异常会抛到 `main` 方法, 若 `main` 方法也不进行处理,  
  就会继续抛出给 JVM, JVM 底层的处理机制就是打印异常的跟踪栈信息.  
  `runtime` 异常就是默认这种处理方式.

- `throws` 可以同时抛出多个异常, 只需要在声明的参数中添加即可.